#------------------------
#GitHub Test Ivan Korolev
#2023.
#------------------------
name: GitHub-Basics
env:
 APPLICATION_NAME    : "MyFlask"
 DEPLOY_PACKAGE_NAME: "flask-deploy${{ github.sha}}"  
   

# Controls when the workflow will run
on: 
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push: 
    branches:  [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
      - name: echo Hello Message
        run: echo "Hello world Test Message"
  
      - name: Execure few commands
        run: |
         echo "Hello1"
         echo "Hello2"
         echo "NAME: ${{ env.APPLICATION_NAME}}"
       
      - name: List current folder 1
        run: ls -la
        
      - name: Git clone my repo
        run: actions/checkout@v2 
          
      - name: List current folder2
        run: ls -la
      
      
        
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    steps:
      - name: Deploy Print Hello Message
        run: echo "Hello Deploy job"
   
      - name: Deploy package
        run: echo "Deploy packege name is ${{ env.DEPLOY_PACKAGE_NAME }}"
        
      - name: Last test AWS
        run: aws --version
   
      - name: Last test ZIP
        run: zip
   
